package com.example.englishbook.uı.translator

class WordTranslator {
    private val translations = mapOf(
        "Space" to "Uzay",
        "tourism" to "turizm",
        "taken" to "almıştır",
        "a" to "bir",
        "giant" to "dev",
        "leap" to "sıçrama",
        "forward" to "ileri",
        "with" to "ile",
        "the" to "the",
        "inaugural" to "açılış",
        "flight" to "uçuşu",
        "of" to "nin",
        "commercial" to "ticari",
        "spacecraft" to "uzay aracının",
        "Mars" to "Mars",
        "historic" to "tarihi",
        "journey" to "yolculuk",
        "marks" to "işaretler",
        "first" to "ilk",
        "time" to "zaman",
        "that" to "ki",
        "civilians" to "sivillerin",
        "have" to "var",
        "ventured" to "cesaret ettiği",
        "yond" to "ötesine",
        "Earth's" to "Dünya'nın",
        "orbit" to "yörüngesinin",
        "for" to "için",
        "recreational" to "eğlence",
        "purposes" to "amaçlı",
        "operated" to "işletilen",
        "by" to "tarafından",
        "private" to "özel",
        "space" to "uzay",
        "company" to "şirket",
        "is" to "dir",
        "equipped" to "donatılmıştır",
        "with" to "ile",
        "state-of-the-art" to "son teknoloji",
        "amenities" to "olanakları",
        "and" to "ve",
        "accommodations" to "konaklamalar",
        "passengers" to "yolcular için",
        "journey" to "yolculuk",
        "Mars" to "Mars",
        "expected" to "kleniyor",
        "take" to "almak",
        "several" to "birkaç",
        "months" to "ay",
        "during" to "sırasında",
        "which" to "hangi",
        "passengers" to "yolcular",
        "will" to "olacak",
        "experience" to "deneyim",
        "zero-gravity" to "sıfır yerçekimi",
        "and" to "ve",
        "breathtaking" to "nefes kesici",
        "views" to "manzaralar",
        "cosmos" to "kozmik",
        "tourism" to "turizm",
        "long" to "uzun",
        "en" to "olmuştur",
        "dream" to "rüya",
        "adventurers" to "maceraperestlerin",
        "visionaries" to "vizyonerlerin",
        "successful" to "başarılı",
        "launch" to "fırlatma",
        "represents" to "temsil eder",
        "major" to "büyük",
        "milestone" to "kültür",
        "in" to "içinde",
        "human" to "insan",
        "space" to "uzay",
        "exploration" to "keşfi",
        "inaugural" to "açılış",
        "flight" to "uçuşu",
        "captured" to "ele geçirmiştir",
        "giant" to "dev",
        "leap" to "sıçrama",
        "with" to "ile",
        "rise" to "yükseliş",
        "of" to "nin",
        "autonomous" to "otonom",
        "vehicles" to "araçlar",
        "also" to "ayrıca",
        "known" to "bilinen",
        "as" to "olarak",
        "self-driving" to "otonom",
        "cars," to "araçlar,",
        "are" to "dir (Yardımcı Fiil)",
        "equipped" to "donatılmıştır",
        "advanced" to "gelişmiş",
        "sensors" to "sensörler",
        "artificial" to "yapay",
        "intelligence" to "zeka",
        "systems" to "sistemleri",
        "enable" to "etkinleştirmek",
        "them" to "onları",
        "navigate" to "gezinmek",
        "roads" to "yollar",
        "without" to "olmadan",
        "human" to "insan",
        "intervention." to "müdahale.",
        "Tech" to "Teknoloji",
        "companies" to "şirketler",
        "automakers" to "otomobil üreticileri",
        "racing" to "yarış",
        "develop" to "geliştirmek",
        "deploy" to "dağıtmak",
        "technology" to "teknoloji",
        "on" to "üzerinde",
        "mass" to "kütle",
        "scale." to "ölçekte.",
        "Early" to "Erken",
        "trials" to "denemeler",
        "pilot" to "pilot",
        "programs" to "programlar",
        "shown" to "gösterilmiştir",
        "promising" to "umut verici",
        "results," to "sonuçlar,",
        "demonstrating" to "göstererek",
        "ability" to "yetenek",
        "reduce" to "azaltmak",
        "accidents" to "kazaları",
        "congestion" to "tıkanıklık",
        "while" to "iken",
        "improving" to "geliştirme",
        "mobility" to "hareketlilik",
        "efficiency." to "verimlilik.",
        "potential" to "potansiyel",
        "nefits" to "faydaları",
        "vast," to "geniş,",
        "ranging" to "değişen",
        "from" to "itibaren",
        "increased" to "artan",
        "safety" to "güvenlik",
        "accessibility" to "erişilebilirlik",
        "reduced" to "azaltılmış",
        "emissions" to "emisyonlar",
        "travel" to "seyahat",
        "costs." to "maliyetler.",
        "However," to "Ancak,",
        "concerns" to "endişeler",
        "remain" to "kalmak",
        "about" to "hakkında",
        "safety" to "güvenlik",
        "regulatory" to "düzenleyici",
        "challenges" to "zorlukları",
        "associated" to "ilişkilendirilen",
        "Critics" to "Eleştirmenler",
        "argue" to "tartışıyor",
        "may" to "olabilir",
        "displace" to "yerinden etmek",
        "jobs" to "işleri",
        "exacerbate" to "kötüleşmek",
        "inequality" to "eşitsizlik",
        "if" to "eğer",
        "not" to "değil",
        "implemented" to "uygulanmış",
        "carefully." to "dikkatli bir şekilde.",
        "Policymakers" to "Politika yapıcılar",
        "grappling" to "boğuşuyorlar",
        "how" to "nasıl",
        "regulate" to "düzenlemek",
        "ensure" to "emin olmak",
        "their" to "onların",
        "safe" to "güvenli",
        "integration" to "entegrasyon",
        "into" to "içine",
        "existing" to "mevcut",
        "transportation" to "taşımacılık",
        "systems." to "sistemler.",
        "Despite" to "Rağmen",
        "these" to "bu",
        "challenges," to "zorluklar,",
        "era" to "çağ",
        "promises" to "sözler",
        "reshape" to "yeniden şekillendirmek",
        "move" to "hareket",
        "live." to "canlı.",
        "Artificial" to "Yapay",
        "intelligence" to "zeka",
        "ing" to "oluyor",
        "used" to "kullanılıyor",
        "predict" to "tahmin etmek",
        "natural" to "doğal",
        "disasters" to "felaketler",
        "with" to "ile",
        "unprecedented" to "eşi nzeri görülmemiş",
        "accuracy," to "doğrulukla,",
        "saving" to "kurtarıcı",
        "lives" to "canları",
        "mitigating" to "hafifletme",
        "damage." to "hasarı.",
        "algorithms" to "algoritmaları",
        "analyze" to "analiz etmek",
        "vast" to "geniş",
        "amounts" to "miktarlar",
        "of" to "nin-nın",
        "data," to "veri,",
        "including" to "dahil",
        "satellite" to "uydu",
        "imagery," to "görüntü,",
        "weather" to "hava",
        "patterns," to "desenler,",
        "seismic" to "sismik",
        "activity." to "faaliyet.",
        "They" to "Onlar",
        "can" to "olabilir",
        "identify" to "tanımlayabilir",
        "warning" to "uyarı",
        "signs" to "işaretleri",
        "of" to "nin",
        "impending" to "yaklaşan",
        "disasters," to "felaketler,",
        "such" to "böyle",
        "hurricanes," to "kasırgalar,",
        "earthquakes," to "depremler,",
        "wildfires." to "yangınlar.",
        "Governments" to "Hükümetler",
        "organizations" to "organizasyonlar",
        "around" to "etrafında",
        "world" to "dünya",
        "adopting" to "nimseyen",
        "systems" to "sistemleri",
        "improve" to "iyileştirmek",
        "disaster" to "afet",
        "preparedness" to "hazırlık",
        "response." to "yanıt.",
        "Early" to "Erken",
        "warning" to "uyarı",
        "alert" to "uyarı",
        "authorities" to "otoriteler",
        "communities" to "topluluklar",
        "evacuate" to "boşaltmak",
        "or" to "ya da",
        "take" to "almak",
        "preventive" to "önleyici",
        "measures." to "önlemler.",
        "use" to "kullanımı",
        "disaster" to "afet",
        "prediction" to "tahmini",
        "" to "zaten",
        "proven" to "kanıtlanmış",
        "successful" to "başarılı",
        "preventing" to "önleme",
        "loss" to "kayıp",
        "life" to "hayat",
        "property" to "mülkiyet",
        "damage." to "hasar.",
        "However," to "Ancak,",
        "challenges" to "zorluklar",
        "remain," to "kalmak,",
        "data" to "veri",
        "accuracy" to "doğruluk",
        "algorithmic" to "algoritmik",
        "bias." to "önyargı.",
        "Scientists" to "Bilim adamları",
        "working" to "çalışıyor",
        "refine" to "iyileştirmek",
        "models" to "modelleri",
        "predictive" to "öngörü",
        "capabilities." to "kabiliyetleri.",
        "integration" to "entegrasyon",
        "management" to "yönetim",
        "strategies" to "stratejileri",
        "testament" to "şahitlik",
        "power" to "güç",
        "technology" to "teknoloji",
        "address" to "adres",
        "global" to "küresel",
        "challenges." to "zorluklar.",
        "A" to "Bir",
        "deep-sea" to "derin deniz",
        "expedition" to "sefer",
        "uncovered" to "ortaya çıkarmıştır",
        "treasure" to "hazine",
        "trove" to "define",
        "new" to "yeni",
        "species" to "türler",
        "uncharted" to "haritasız",
        "depths" to "derinlikleri",
        "ocean." to "okyanus.",
        "Scientists" to "Bilim adamları",
        "aboard" to "kara",
        "research" to "araştırma",
        "vessel" to "gemi",
        "discovered" to "keşfedilmiş",
        "bizarre" to "garip",
        "creatures" to "yaratıklar",
        "never" to "asla",
        "seen" to "görülen",
        "fore." to "önce.",
        "Among" to "Arasında",
        "finds" to "bulgular",
        "bioluminescent" to "biyoluminiscent",
        "jellyfish," to "deniz anası,",
        "giant" to "dev",
        "squid," to "mürekkep balığı,",
        "exotic" to "egzotik",
        "fish" to "balıklar",
        "striking" to "çarpıcı",
        "colors" to "renkler",
        "patterns." to "desenler.",
        "expedition" to "sefer",
        "was" to "idi",
        "part" to "parça",
        "global" to "küresel",
        "effort" to "çaba",
        "explore" to "keşfetmek",
        "world's" to "dünya'nın",
        "oceans" to "okyanuslar",
        "document" to "lge",
        "biodiversity." to "Biyoçeşitlilik.",
        "Researchers" to "Araştırmacılar",
        "used" to "kullanılan-kullanılmış",
        "state-of-the-art" to "Son teknoloji-Teknoloji Harikası",
        "technology," to "Teknoloji,",
        "including" to "dahil",
        "submersibles" to "bataryalar",
        "underwater" to "Sualtı",
        "drones," to "insansız hava araçları,",
        "navigate" to "Navigasyon",
        "depths." to "Derinlikler.",
        "discoveries" to "keşifler",
        "shed" to "Dökmek",
        "light" to "ışık",
        "mysteries" to "gizemler",
        "sea" to "deniz",
        "inhabitants." to "sakinleri.",
        "Scientists" to "Bilim adamları",
        "excited" to "Heyecanlı",
        "about" to "Hakkında",
        "potential" to "Potansiyel",
        "implications" to "Etkiler",
        "conservation" to "koruma",
        "medicine." to "iLAÇ",
        "hope" to "Umut",
        "learn" to "Öğrenmek",
        "newly" to "yeni",
        "discovered" to "keşfedilen",
        "species" to "türler",
        "roles" to "rolleri",
        "marine" to "deniz",
        "ecosystem." to "ekosistem.",
        "deep-sea" to "derin deniz",
        "expedition" to "sefer",
        "reignited" to "yeniden ateşledi",
        "interest" to "ilgi",
        "ocean" to "okyanus",
        "inspired" to "ilham",
        "new" to "yeni",
        "generations" to "kuşaklar",
        "scientists." to "bilim adamları.",
        "achieved" to "elde edilmiştir-ulaşıldı",
        "major" to "büyük",
        "breakthrough" to "atılım",
        "quantum" to "kuantum",
        "computing" to "bilgisayar",
        "could" to "olabilir",
        "revolutionize" to "devrim",
        "way" to "yol",
        "process" to "işlemek",
        "information." to "bilgi.",
        "Quantum" to "Kuantum",
        "computers" to "bilgisayarlar",
        "harness" to "kullanmak",
        "power" to "güç",
        "mechanics" to "mekanik",
        "perform" to "gerçekleştirmek",
        "complex" to "karmaşık",
        "calculations" to "hesaplamalar",
        "unprecedented" to "eşi nzeri görülmemiş",
        "speeds." to "hızlar.",
        "Researchers" to "Araştırmacılar",
        "developed" to "geliştirilmiş",
        "new" to "yeni",
        "quantum" to "kuantum",
        "algorithm" to "algoritma",
        "solves" to "çözümler",
        "previously" to "daha önce",
        "unsolvable" to "çözülemeyen",
        "problems." to "sorunlar.",
        "algorithm" to "algoritma",
        "potential" to "potansiyel",
        "accelerate" to "hız",
        "Robots" to "Robotlar",
        "increasingly" to "giderek daha çok",
        "taking" to "üstleniyor",
        "over" to "üzerinde",
        "jobs" to "işleri",
        "various" to "çeşitli",
        "industries" to "endüstrilerde",
        "leading" to "neden oluyor",
        "some" to "bazı",
        "calling" to "adlandırdığı",
        "robot" to "robot",
        "revolution" to "devrim",
        "workplace" to "işyeri",
        "Advances" to "Gelişmeler",
        "robotics" to "robotik",
        "artificial" to "yapay",
        "intelligence" to "zeka",
        "have" to "olmuştur",
        "made" to "daha",
        "robots" to "robotlar",
        "more" to "daha",
        "capable" to "yetenekli",
        "than" to "daha",
        "ever" to "hiç",
        "fore" to "önce",
        "They" to "Onlar",
        "can" to "yapabilir-e'bilir",
        "perform" to "gerçekleştirebilirler",
        "tasks" to "görevleri",
        "ranging" to "değişen",
        "manufacturing" to "üretim",
        "assembly" to "montaj",
        "customer" to "müşteri",
        "service" to "hizmet",
        "healthcare" to "sağlık hizmetleri",
        "Companies" to "Şirketler",
        "investing" to "yatırım yapıyor",
        "heavily" to "yoğun bir şekilde",
        "automation" to "otomasyon",
        "increase" to "artırmak",
        "efficiency" to "verimlilik",
        "reduce" to "azaltmak",
        "costs" to "maliyetleri",
        "While" to "Oysa",
        "robots" to "robotlar",
        "offer" to "sunarlar",
        "many" to "birçok",
        "nefits" to "faydalar",
        "they" to "onlar",
        "also" to "ayrıca",
        "raise" to "arttırırlar",
        "concerns" to "endişeleri",
        "about" to "hakkında",
        "job" to "iş",
        "displacement" to "yer değiştirme",
        "future" to "gelecek",
        "work" to "iş",
        "Some" to "Bazı",
        "experts" to "uzmanlar",
        "predict" to "öngörüyor",
        "that" to "ki",
        "millions" to "milyonlarca",
        "of" to "of",
        "jobs" to "işler",
        "will" to "olacak",
        "" to "olmak",
        "lost" to "kaytmek",
        "automation" to "otomasyon",
        "coming" to "gelen",
        "years" to "yıllarda",
        "Others" to "Diğerleri",
        "argue" to "tartışıyorlar",
        "robots" to "robotlar",
        "create" to "oluşturacak",
        "new" to "yeni",
        "opportunities" to "fırsatlar",
        "industries" to "endüstriler",
        "rise" to "yükseliş",
        "robots" to "robotlar",
        "reshaping" to "yeniden şekillendiriyor",
        "labor" to "iş",
        "market" to "pazar",
        "sparking" to "tetikleyerek-kıvılcım",
        "group" to "grup",
        "tourists" to "turistler",
        "claiming" to "iddia ederek",
        "time" to "zaman",
        "travelers" to "seyahatçiler",
        "en" to "olmuştur",
        "discovered" to "keşfedilmiş",
        "historical" to "tarihi",
        "photographs" to "fotoğraflar",
        "past." to "geçmişten-geçmiş.",
        "The" to "The",
        "tourists" to "turistler",
        "appear" to "görünmek",
        "in" to "içinde",
        "pictures" to "resimler",
        "taken" to "çekilen",
        "decades" to "on yıllar",
        "even" to "bile",
        "centuries" to "yüzyıllar",
        "ago," to "önce,",
        "wearing" to "giyerken",
        "modern" to "modern",
        "clothing" to "giysiler",
        "accessories." to "aksesuarlar.",
        "Some" to "Bazıları",
        "seen" to "görülüyor",
        "posing" to "poz veriyor",
        "in front of" to "önünde",
        "famous" to "ün",
        "landmarks," to "anıtların önünde,",
        "while" to "iken",
        "others" to "diğerleri",
        "mingle" to "karışırlar",
        "historical" to "tarihi",
        "figures." to "figürlerle.",
        "authenticity" to "gerçekliği",
        "photographs" to "fotoğraflar",
        "verified" to "doğrulandı",
        "by" to "tarafından",
        "experts," to "uzmanlar,",
        "leaving" to "bırakarak",
        "many" to "birçok",
        "puzzled" to "şaşkın",
        "phenomenon." to "fenomen",
        "travelers" to "seyahatçiler",
        "insist" to "ısrar etmek",
        "future" to "gelecek",
        "traveled" to "seyahat",
        "back" to "geri",
        "sightseeing." to "gezinti.",
        "They" to "Onlar",
        "refuse" to "reddediyorlar",
        "disclose" to "açıklamak",
        "how" to "nasıl",
        "they" to "onlar",
        "achieved" to "başardılar",
        "time" to "zaman",
        "travel" to "seyahat",
        "why" to "neden",
        "chose" to "seçtiler",
        "visit" to "ziyaret",
        "specific" to "lirli",
        "periods." to "dönemler.",
        "Conspiracy" to "Komplo",
        "theories" to "teorileri",
        "abound," to "çevrelerde bulunur,",
        "speculating" to "spekülasyon",
        "part" to "bölüm",
        "government" to "hükümet",
        "experiment" to "deney",
        "alternate" to "alternatif",
        "reality." to "gerçeklik.",
        "Historians" to "Tarihçiler",
        "studying" to "çalışıyorlar",
        "photographs" to "fotoğraflar",
        "clues" to "ipuçları",
        "about" to "hakkında",
        "origins" to "kökenleri",
        "motivations." to "motivasyonlar.",
        "discovery" to "keşif",
        "Archaeologists" to "Arkeologlar",
        "made" to "yaptılar",
        "groundbreaking" to "çığır açan",
        "unearthed" to "gün yüzüne çıkardılar",
        "ancient" to "antik",
        "artifact" to "eser",
        "lieved" to "inanılan",
        "hold" to "tutmak",
        "key" to "anahtar",
        "travel." to "yolculuğu.",
        "artifact" to "eser",
        "found" to "bulundu",
        "buried" to "gömülü",
        "remote" to "uzak",
        "cave" to "mağara",
        "deep" to "derin",
        "in" to "içinde",
        "mountains." to "dağlar.",
        "covered" to "kaplı",
        "mysterious" to "gizemli",
        "symbols" to "semboller",
        "inscriptions." to "yazıtlar.",
        "Experts" to "Uzmanlar",
        "studied" to "incelediler",
        "and" to "ve",
        "determined" to "lirlediler",
        "time-travel" to "zaman yolculuğu",
        "device" to "cihaz",
        "used" to "kullanılan",
        "ancient" to "antik",
        "civilization." to "medeniyet.",
        "device" to "cihaz",
        "appeared" to "görünüyordu",
        "" to "olmak",
        "activated" to "etkinleştirilmiş",
        "by" to "tarafından",
        "series" to "dizi",
        "intricate" to "karmaşık",
        "rituals" to "ritüeller",
        "and" to "ve",
        "incantations." to "büyüler.",
        "Scientists" to "Bilim insanları",
        "skeptical" to "şüpheci",
        "at" to "'de-'da",
        "but" to "ama",
        "conducted" to "yaptılar",
        "experiments" to "deneyler",
        "test" to "test etmek",
        "artifact's" to "eserin",
        "capabilities." to "yeteneklerini.",
        "their" to "onların",
        "amazement," to "hayretlerine,",
        "able" to "yapabildiler",
        "send" to "göndermek",
        "small" to "küçük",
        "objects" to "nesneler",
        "forward" to "ileriye",
        "backward" to "geri",
        "time." to "zaman.",
        "implications" to "sonuçlar",
        "discovery" to "keşif",
        "profound." to "derin.",
        "raised" to "kaldırdı",
        "questions" to "sorular",
        "about" to "hakkında",
        "nature" to "doğa",
        "possibility" to "olasılık",
        "altering" to "değiştirme",
        "past" to "geçmiş",
        "future." to "gelecek.",
        "Scientists" to "Bilim insanları",
        "and" to "ve",
        "historians" to "tarihçiler",
        "debated" to "tartıştılar",
        "ethical" to "etik",
        "practical" to "pratik",
        "implications" to "sonuçlar",
        "time" to "zaman",
        "travel." to "yolculuğu.",
        "The" to "The",
        "ancient" to "antik",
        "artifact" to "eser",
        "remained" to "kaldı",
        "source" to "kaynak",
        "fascination" to "büyülenme",
        "intrigue" to "entrika",
        "researchers" to "araştırmacılar",
        "around" to "çevresinde",
        "world." to "dünya",
        "massive" to "devasa",
        "sinkhole" to "obruk",
        "opened" to "açıldı",
        "up" to "yukarı",
        "middle" to "orta",
        "city" to "şehir",
        "street," to "sokak,",
        "swallowing" to "yutan",
        "everything" to "her şey",
        "path." to "yol.",
        "appeared" to "göründü",
        "suddenly," to "aniden,",
        "without" to "olmadan",
        "warning." to "uyarı.",
        "Cars" to "Arabalar",
        "buildings" to "binalar",
        "swallowed" to "yutuldu",
        "whole," to "bütün,",
        "disappearing" to "kaybolarak",
        "into" to "içine",
        "depths" to "derinlikler",
        "low." to "aşağıda.",
        "Emergency" to "Acil",
        "crews" to "ekipler",
        "rushed" to "koştu",
        "scene," to "sahne,",
        "but" to "ama",
        "too" to "çok",
        "late" to "geç",
        "save" to "kurtarmak",
        "anything." to "herhangi bir şey.",
        "grew" to "büyüdü",
        "larger" to "daha büyük",
        "minute," to "dakika,",
        "threatening" to "tehdit eden",
        "engulf" to "yutmak",
        "more" to "daha fazla",
        "city." to "şehir.",
        "Residents" to "Sakinler",
        "evacuated" to "tahliye",
        "precaution." to "önlem.",
        "Geologists" to "Jeologlar",
        "baffled" to "şaşkın",
        "sudden" to "ani",
        "appearance" to "görünüş",
        "sinkhole." to "obruk.",
        "They" to "Onlar",
        "suspected" to "şüphelendiler",
        "caused" to "neden",
        "underground" to "yeraltı",
        "erosion" to "erozyon",
        "collapsed" to "çökmüş-hapsedilmiş",
        "sewer" to "kanalizasyon",
        "line." to "hattı.",
        "Engineers" to "Mühendisler",
        "worked" to "çalıştılar",
        "tirelessly" to "yorulmadan",
        "fill" to "doldurmak",
        "repair" to "onarım",
        "damage." to "hasar.",
        "incident" to "olay",
        "left" to "bıraktı",
        "city" to "şehir",
        "shock" to "şok",
        "dislief." to "inanmazlık.",
        "reminder" to "hatırlatıcı",
        "unpredictable" to "öngörülemeyen",
        "forces" to "güçler",
        "nature." to "doğa.",
        "Archaeologists" to "Arkeologlar",
        "made" to "yapmak",
        "groundbreaking" to "çığır açan",
        "discovery" to "keşif",
        "underwater." to "su altında.",
        "They" to "Onlar",
        "found" to "buldular",
        "remains" to "kalıntılar",
        "an" to "bir",
        "ancient" to "antik",
        "city" to "şehir",
        "buried" to "gömülü",
        "neath" to "altında",
        "ocean" to "okyanus",
        "floor." to "tabanı.",
        "city" to "şehir",
        "lieved" to "inanılıyor",
        "thousands" to "binlerce",
        "years" to "yıl",
        "remarkably" to "dikkat çekici",
        "well-preserved," to "iyi korunmuş,",
        "with" to "ile",
        "intact" to "sağlam",
        "buildings" to "binalar",
        "artifacts." to "eserler.",
        "Scientists" to "Bilim insanları",
        "excited" to "heyecanlı",
        "about" to "hakkında",
        "potential" to "potansiyel",
        "insights" to "bilgiler",
        "could" to "olabilirdi-e-bilirdi",
        "provide" to "sağlamak",
        "ancient" to "antik",
        "civilizations." to "medeniyetler.",
        "suspect" to "şüpheleniyorlar",
        "city" to "şehir",
        "once" to "bir zamanlar",
        "thriving" to "gelişen",
        "hub" to "merkez",
        "trade" to "ticaret",
        "culture." to "kültür.",
        "Divers" to "Dalgıçlar",
        "exploring" to "keşfetmek",
        "underwater" to "su altı",
        "ruins," to "haraler,",
        "uncovering" to "ortaya çıkarmak",
        "more" to "daha fazla",
        "secrets" to "sırlar",
        "each" to "her",
        "dive." to "dalış.",
        "discovery" to "keşif",
        "sparked" to "ateşledi",
        "international" to "uluslararası",
        "interest" to "ilgi",
        "speculation." to "spekülasyon.",
        "People" to "İnsanlar",
        "around" to "çevresinde",
        "world" to "dünya",
        "fascinated" to "büyülenmiş",
        "lost" to "kayıp",
        "city" to "şehir",
        "mysteries." to "gizemler.",
        "A" to "Bir",
        "spooky" to "ürkütücü",
        "house" to "ev",
        "en" to "olmuş",
        "causing" to "neden olmak",
        "quite" to "oldukça",
        "stir" to "karışıklık",
        "neighborhood." to "mahalle.",
        "Locals" to "Yerliler",
        "claim" to "iddia etmek",
        "heard" to "duyduk",
        "strange" to "garip",
        "noises" to "sesler",
        "coming" to "gelmek",
        "night." to "gece.",
        "Some" to "Bazıları",
        "say" to "söylemek",
        "seen" to "görmek",
        "ghostly" to "hayalet",
        "figures" to "şekiller",
        "windows." to "pencereler.",
        "long" to "uzun",
        "history" to "tarih",
        "paranormal" to "paranormal",
        "activity." to "aktivite.",
        "Legend" to "Efsane",
        "haunted" to "perili",
        "ghost" to "hayalet",
        "former" to "önceki",
        "owner." to "sahip.",
        "Despite" to "Rağmen",
        "warnings," to "uyarılar,",
        "group" to "grup",
        "brave" to "cesur",
        "teenagers" to "gençler",
        "decided" to "karar verdi",
        "explore" to "keşfetmek",
        "house." to "ev.",
        "brought" to "getirdi",
        "cameras" to "kameralar",
        "flashlights" to "el fenerleri",
        "document" to "lgelemek",
        "their" to "onların",
        "adventure." to "macera.",
        "What" to "Ne",
        "discovered" to "keşfetmek",
        "inside" to "içinde",
        "remains" to "kalıntılar",
        "mystery." to "gizem.",
        "teenagers" to "gençler",
        "claim" to "iddia etmek",
        "encountered" to "karşılaşmak",
        "strange" to "garip",
        "phenomena" to "fenomenler",
        "unexplained" to "açıklanamayan",
        "occurrences." to "olaylar.",
        "lieve" to "inanmak",
        "house" to "ev",
        "indeed" to "gerçekten",
        "haunted." to "perili-lanetli",
        "small" to "küçük",
        "town," to "kasabada,",
        "people" to "insanlar",
        "reported" to "bildirdi",
        "seeing" to "gördüklerini",
        "mysterious" to "gizemli",
        "lights" to "ışıklar",
        "sky" to "gökyüzü",
        "last" to "gece.",
        "night." to "gece.",
        "lights" to "ışıklar",
        "appeared" to "göründü",
        "suddenly" to "aniden",
        "moved" to "hareket etti",
        "strange" to "tuhaf",
        "patterns." to "şekillerde.",
        "Witnesses" to "Tanıklar",
        "descrid" to "tanımladı",
        "them" to "onları",
        "glowing" to "parlayan-ışıltılı",
        "orbs" to "küreler",
        "different" to "farklı",
        "colors." to "renkler.",
        "Some" to "Bazıları",
        "thought" to "düşündü",
        "UFO" to "UFO",
        "sighting." to "Görme .",
        "local" to "yerel",
        "authorities" to "yetkililer",
        "received" to "aldı",
        "numerous" to "çok",
        "calls" to "çağrı",
        "about" to "hakkında",
        "phenomenon." to "fenomen.",
        "Scientists" to "Bilim adamları",
        "investigating" to "araştırıyor",
        "cause" to "sep",
        "lights." to "ışıkların.",
        "suspect" to "şüpheleniyor",
        "natural" to "doğal",
        "phenomenon" to "fenomen",
        "man-made" to "insan yapımı",
        "event." to "olay.",
        "townspeople" to "kasabalılar",
        "curious" to "meraklı",
        "excited" to "heyecanlı",
        "about" to "hakkında",
        "mysterious" to "gizemli",
        "gather" to "toplanır",
        "every" to "her",
        "night" to "gece",
        "watch" to "İzlemek",
        "the" to "the",
        "sky," to "gökyüzünü,",
        "hoping" to "umut",
        "see" to "görmek",
        "them" to "onları",
        "again." to "yine.",
        "Emily" to "Emily",
        "went" to "gitti",
        "park" to "parka",
        "her" to "onun",
        "family." to "aile.",
        "brought" to "getirdi",
        "favorite" to "favori",
        "teddy" to "ayı",
        "ar," to "ayı,",
        "Teddy." to "Teddy.",
        "While" to "Oynarken,",
        "playing," to "oynarken,",
        "Emily" to "Emily",
        "accidentally" to "kazara",
        "left" to "bıraktı",
        "nch." to "bank.",
        "didnt" to "olumsuz bir yardımcı fiil",
        "realize" to "fark etmedi",
        "until" to "e-kadar",
        "felt" to "hissetti",
        "sad" to "üzgün",
        "scared" to "korkmuş",
        "cause" to "çünkü",
        "lost." to "kaybolmuştu.",
        "told" to "söyledi",
        "parents" to "eveynler",
        "decided" to "karar vermek",
        "go" to "gitmek",
        "look" to "bakmak.",
        "Emily" to "Emily",
        "searched" to "araştırdı",
        "everywhere" to "her yerde",
        "find" to "bulmak.",
        "Suddenly," to "Birden,",
        "rememred" to "hatırladı",
        "she" to "o",
        "left" to "bıraktı",
        "ran" to "koştu",
        "found" to "buldu",
        "waiting" to "kliyor",
        "hugged" to "kucakladı",
        "tightly," to "sıkıca,",
        "ing" to "hissederek",
        "happy" to "mutlu",
        "again." to "yine.",
        "promised" to "söz verdi",
        "carefully" to "dikkatli",
        "on." to "üzerinde.",
        "thanked" to "teşekkür etmek",
        "helping" to "yardımcı",
        "great" to "Büyük-Harika",
        "above" to "üst",
        "opened" to "açtı",
        "goddess" to "tanrıça",
        "opened" to "açtı",
        "ear" to "kulak",
        "above" to "üst",
        "Inanna" to "Inanna",
        "opened" to "açtı",
        "My" to "nim",
        "Lady" to "Bayan değil Kadın",
        "abandoned" to "terk etti-terk edilmiş",
        "heaven" to "cennet",
        "earth" to "Toprak",
        "descend" to "inmek",
        "underworld." to "Yeraltı.",
        "Inanna" to "Inanna",
        "office" to "Ofis",
        "priestess" to "Rahi",
        "Volleyball" to "Voleybol",
        "emerged" to "ortaya çıkmak",
        "the United States" to "Amerika Birleşik Devletleri",
        "late" to "geç",
        "19th" to "19.",
        "century" to "yüzyıl",
        "invented" to "İcat edildi",
        "William G. Morgan" to "William G. Morgan",
        "YMCA(Young Men Christian Association)" to "YMCA (Genç Erkekler Hıristiyan Derneği)",
        "Massachusetts" to "Massachusetts'te",
        "wanted" to "istedi-istemek",
        "a less aggressive alternative to basketball" to "Daha az saldırgan bir alternatif ",
        "so" to "bu yüzden",
        "developed" to "geliştirdi",
        "the idea of passing a ball over a net on both sides" to "her iki tarafında bir file üzerinden top geçiş fikrini geliştirdi",
        "Initially" to "Başlangıçta",
        "the game" to "oyun",
        "soon" to "Kısa sürede-Yakında",
        "renamed" to "yeniden adlandırıldı",
        "volleyball" to "voleybol",
        "Volleyball" to "Voleybol",
        "gained" to "kazandı",
        "rapid popularity" to "hızlı popülerlik",
        "spread" to "yayıldı",
        "to other countries" to "diğer ülkelere",
        "quickly" to "hızlı bir şekilde",
        "By the 1920s" to "1920'lerde",
        "an international sport" to "Uluslararası bir spor ",
        "with tournaments held among various nations" to "çeşitli uluslararası turnuvalar düzenlenen",
        "The International Volleyball Federation (FIVB)" to "Uluslararası Voleybol Federasyonu (FIVB)",
        " established in 1947" to "1947'de kuruldu",
        "further promoting the global development of volleyball" to "voleybolun küresel gelişimini daha da teşvik ederek",
        "an internationally recognized sport played by millions worldwide" to " Uluslararası tanınan bir spor haline gelmiştir",
        "It is an easy and enjoyable team sport" to "Bu, kolay ve keyifli bir takım sporudur",
        "that can  played in various settings, from indoor gyms to aches." to "kapalı spor salonlarından plajlara kadar çeşitli ortamlarda oynanabilir.",
        "Franz Kafka" to "Franz Kafka",
        "famous" to "ünlü",
        "r" to "yazar",
        "Prague" to "Prag",
        "Czech Republic" to "Çek Cumhuriyeti",
        "lived" to "yaşadı",
        "wrote" to "yazdı",
        "stories" to "hikayeler",
        "novels" to "romanlar",
        "still" to "hala",
        "today" to "bugün",
        "most" to "en",
        "book" to "kitap",
        "The Metamorphosis" to "Dönüşüm",
        "man" to "adam",
        "wakes" to "uyanır",
        "one" to "bir",
        "day" to "gün",
        "find" to "Bulmak",
        "turned" to "dönüşmüş",
        "giant" to "kocaman",
        "insect" to "böcek",
        "often" to "genellikle",
        "strange" to "garip",
        "think" to "Düşünmek",
        "loneliness" to "yalnızlık",
        "fear" to "Korku",
        "confusion" to "kafa karışıklığı",
        "Kafka's" to "Kafka'nın",
        "style" to "tarzı",
        "simple" to "basit",
        "but" to "ama",
        "powerful" to "güçlü",
        "important" to "önemli",
        "rs" to "yazarlar",
        "Many" to "Birçok",
        "people" to "insan",
        "still" to "hala",
        "work" to "Çalışma-Çalışmak",
        "translated" to "çevrilmiş",
        "many" to "birçok",
        "languages" to "diller",
        "loved" to "sevilen",
        "all" to "her",
        "world" to "Dünya",
        "iPhone" to "iPhone",
        "Apple" to "Apple",
        "first" to "ilk",
        "fancy" to "şatafatlı",
        "phone" to "telefon",
        "changed" to "değiştirdi",
        "phones" to "telefonları",
        "big" to "büyük",
        "touch" to "Dokunmatik-Dokunmak",
        "screen" to "ekran",
        "cool" to "havalı",
        "stuff" to "şeyler",
        "guy" to "adam",
        "named" to "adlı",
        "Steve Jobs" to "Steve Jobs",
        "showed" to "Gösterdi",
        "people" to "İnsanlar",
        "iPhone" to "iPhone",
        "small" to "küçük",
        "camera" to "kamera",
        "used" to "kullandı",
        "Apple's" to "Apple'ın",
        "special" to "özel",
        "software" to "yazılımı",
        "also" to "aynı zamanda",
        "iPod" to "iPod",
        "could" to "yapabilirdi",
        "internet" to "internet",
        "everywhere" to "her yerde",
        "use" to "kullanmak",
        "looked" to "göründü",
        "cool" to "havalı",
        "kept making" to "yapmaya devam etti",
        "iPhones" to "iPhone'lar",
        "changed" to "değiştirdi",
        "we" to "biz",
        "online" to "çevrimiçi",
        "things" to "şey",
        "in" to "teknolojide",
        "tech" to "teknoloji",
        "Once" to "Bir zamanlar",
        "upon" to "bir",
        "there" to "vardı-var",
        "little" to "küçük",
        "girl" to "kız",
        "lived" to "yaşıyordu",
        "small" to "küçük",
        "village" to "Köy",
        "surrounded" to "Çevrili",
        "green" to "yeşil",
        "fields" to "Tarlalar-Alanlar",
        "tall" to "uzun",
        "trees" to "ağaçlar",
        "while-playing" to "oynarken",
        "backyard" to "Arka bahçe",
        "found" to "Buldu",
        "tiny" to "küçük",
        "kitten" to "kedi yavrusu",
        "hiding" to "saklanan",
        "bushes" to "Çalılar",
        "kitten" to "yavrusu",
        "scared" to "korkmuş",
        "hungry" to "Aç",
        "sorry" to "Üzülmek",
        "decided" to "Karar verdi- Karar vermek",
        "gently" to "nazikçe",
        "picked" to "aldı",
        "brought" to "getirdi",
        "gave" to "Verdi-Vermek",
        "milk" to "süt",
        "warm" to "sıcak-ılık",
        "blanket" to "battaniye",
        "sleep" to "Uyumak",
        "purred" to "Mırladı-Mırlamak",
        "softly" to "Yumuşakça",
        "nuzzled" to "sokuldu",
        "against" to "karşı",
        "hand" to "El",
        "asked" to "Sordu-Sormak",
        "agreed" to "Kabul etti",
        "Whiskers" to "Bıyıklar",
        "Every" to "Her",
        "" to "Birlikte-rar",
        "friends" to "arkadaş",
        "went" to "Gitti-Gitmek",
        "school" to "Okul",
        "Years" to "Yıllar",
        "passed" to "Geçti-Geçmek",
        "and" to "ve",
        "Lily" to "Lily",
        "and" to "ve",
        "Whiskers" to "Bıyıklar",
        "grew" to "büyüdü",
        "up" to "birlikte",
        "together" to "birlikte",
        "shared" to "paylaştı",
        "adventures" to "macera",
        "wonderful" to "harika",
        "memories" to "anılar",
        "" to "idi",
        "grateful" to "minnettar",
        "for" to "için",
        "the" to "gün",
        "day" to "gün",
        "she" to "o",
        "found" to "buldu",
        "the" to "kayıp",
        "lost" to "kayıp",
        "kitten" to "kedi",
        "in" to "bahçesinde",
        "her" to "bahçesinde",
        "backyard" to "bahçesinde",
        "Whiskers" to "Bıyıklar",
        "had" to "getirdi",
        "brought" to "getirdi",
        "so" to "çok",
        "much" to "çok",
        "joy" to "neşe",
        "and" to "ve",
        "love" to "sevgi",
        "into" to "onun",
        "her" to "onun",
        "life" to "hayatına",
        "And" to "Ve",
        "so" to "böylece",
        "Lily" to "Lily",
        "and" to "ve",
        "Whiskers" to "Bıyıklar",
        "lived" to "yaşadı",
        "happily" to "mutlu",
        "ever" to "sonsuza",
        "after" to "kadar",
        "surrounded" to "çevrili",
        "by" to "sevgi",
        "love" to "ve",
        "and" to "dostluk",
        "friendship" to "ile",
        "in" to "onların",
        "their" to "onların",
        "cozy" to "rahat",
        "little" to "küçük",
        "village" to "köyde",
        "The" to "İlk",
        "first" to "ilk",
        "steps" to "adımlar",
        "of" to "psikolojinin",
        "psychology" to "psikolojinin",
        "were" to "atıldı",
        "taken" to "atıldı",
        "with" to "merak",
        "curiosity" to "merak",
        "and" to "ve",
        "interest" to "ilgi",
        "in" to "anlama",
        "understanding" to "anlama",
        "human" to "insan",
        "mental" to "zihinsel",
        "processes" to "süreçler",
        "and" to "ve",
        "haviors" to "davranışlar",
        "People" to "İnsanlar",
        "have" to "çabalıyor",
        "en" to "çabalıyor",
        "trying" to "çabalıyor",
        "to" to "anlamak",
        "understand" to "anlamak",
        "each" to "birbirlerinin",
        "others" to "birbirlerinin",
        "haviors" to "davranışlarını",
        "ings" to "duygularını",
        "and" to "ve",
        "thoughts" to "düşüncelerini",
        "for" to "binlerce",
        "thousands" to "binlerce",
        "of" to "yıldır",
        "years" to "yıldır",
        "However" to "Ancak",
        "the" to "psikolojinin",
        "establishment" to "kurulması",
        "of" to "psikolojinin",
        "psychology" to "kurulması",
        "as" to "modern",
        "a" to "bir",
        "modern" to "modern",
        "scientific" to "bilimsel",
        "discipline" to "disiplin",
        "dates" to "19. yüzyıla",
        "back" to "dayanmaktadır",
        "to" to "dayanmaktadır",
        "the" to "19. yüzyıla",
        "19th" to "19.",
        "century" to "yüzyıla",

        "The" to "Bilimsel",
        "scientific" to "bilimsel",
        "foundations" to "temelleri",
        "of" to "psikolojinin",
        "psychology" to "psikolojinin",
        "were" to "atıldı",
        "laid" to "atıldı",
        "when" to "Wilhelm",
        "Wilhelm" to "Wilhelm",
        "Wundt" to "Wundt",
        "established" to "kurdu",
        "the" to "ilk",
        "first" to "ilk",
        "experimental" to "deneysel",
        "psychology" to "psikoloji",
        "laboratory" to "laboratuvarını",
        "at" to "Leipzig",
        "Leipzig" to "Leipzig",
        "University" to "Üniversitesinde",
        "in" to "Almanya'da",
        "Germany" to "Almanya'da",
        "in" to "1879'da",
        "1879" to "1879'da",
        "Wundt" to "Wundt",
        "pioneered" to "öncülük etti",
        "the" to "insan",
        "study" to "çalışmalarına",
        "of" to "insan",
        "the" to "zihnini",
        "human" to "zihnini",
        "mind" to "çalışmalarına",
        "using" to "kullanarak",
        "experimental" to "deneysel",
        "methods" to "yöntemler",
        "thus" to "bu şekilde",
        "establishing" to "kurarak",
        "psychology" to "psikolojiyi",
        "science" to "olarak",

        "Psychology" to "Psikoloji",
        "then" to "daha sonra",
        "continued" to "devam etti",
        "to" to "gelişmeye",
        "develop" to "gelişmeye",
        "under" to "farklı",
        "different" to "okul",
        "schools" to "okul",
        "and" to "ve",
        "perspectives" to "perspektifler",
        "Various" to "Çeşitli",
        "theoretical" to "teorik",
        "approaches" to "yaklaşımlar",
        "such" to "gibi",
        "as" to "gibi",
        "structuralism" to "yapısalcılık",
        "functionalism" to "işlevselcilik",
        "haviorism" to "davranışçılık",
        "psychoanalysis" to "psikanaliz",
        "and" to "ve",
        "cognitive" to "bilişsel",
        "psychology" to "psikoloji",
        "were" to "geliştirildi",
        "developed" to "geliştirildi",

        "The" to "Psikolojinin",
        "development" to "gelişimi",
        "of" to "psikolojinin",
        "psychology" to "gelişimi",
        "has" to "desteklendi",
        "en" to "desteklendi",
        "supported" to "desteklendi",
        "by" to "araştırma",
        "advancements" to "ilerlemeler",
        "in" to "araştırma",
        "research" to "yöntemleri",
        "methodologies" to "yöntemleri",
        "and" to "ve",
        "technologies" to "teknolojiler",
        "Tools" to "Araçlar",
        "such" to "gibi",
        "as" to "gibi",
        "computers" to "bilgisayarlar",
        "neurological" to "nörolojik",
        "imaging" to "görüntüleme",
        "techniques" to "teknikleri",
        "and" to "ve",
        "statistical" to "istatistiksel",
        "analysis" to "analiz",
        "methods" to "yöntemler",
        "have" to "mümkün",
        "enabled" to "kıldı",
        "more" to "daha",
        "in-depth" to "derinlemesine",
        "and" to "ve",
        "complex" to "karmaşık",
        "psychological" to "psikolojik",
        "research" to "araştırma",
        "psychology" to "Psikoloji",
        "discipline" to "Disiplin",
        "encompasses" to "Kapsar",
        "wide" to "geniş",
        "range" to "yelpaze",
        "involves" to "İçerir-İçermek",
        "various" to "çeşitli",
        "research" to "araştırma",
        "application" to "uygulama",
        "areas" to "alanlarda",
        "aimed" to "amaçlayan",
        "understanding" to "anlamayı",
        "explaining" to "açıklamayı",
        "improving" to "İyileştirmeyi-Geliştirmeyi",
        "human" to "insan",
        "haviors" to "davranışlarını",
        "advancement" to "gelişimi",
        "result" to "sonuç",
        "continuous" to "sürekli",
        "exploration" to "araştırma-keşif",
        "process" to "süreç",
        "understand" to "anlamak",
        "oneself" to "kendini-kendisi",
        "environment" to "Çevre",
        "Inflation" to "Enflasyon",
        "occurs" to "meydana gelmek",
        "general" to "genel",
        "price" to "fiyat",
        "level" to "seviye",
        "services" to "hizmetler",
        "economy" to "ekonomi",
        "rises" to "yükselir",
        "continuously" to "sürekli",
        "increase" to "artış",
        "prices" to "fiyatlarda",
        "reduces" to "azaltır",
        "purchasing" to "satın alma",
        "power" to "Güç",
        "currency" to "Para birimi-Para",
        "meaning" to "yani",
        "money" to "para",
        "buy" to "alabilir",
        "fewer" to "daha az",
        "factors" to "faktörler",
        "excess" to "aşırı",
        "demand" to "talep",
        "outstrips" to "aşar",
        "supply" to "Arz",
        "leading" to "Önde gelen",
        "higher" to "daha yüksek",
        "Cost-push" to "Maliyet itişi",
        "happens" to "olur",
        "production" to "üretim",
        "costs" to "Maliyet",
        "prompting" to "Zorlayan-Teşvik eden",
        "businesses" to "işletmeler",
        "Monetary" to "Parasal",
        "contribute" to "bulunabilir",
        "circulating" to "dolaşan",
        "Additionally" to "Ek olarak",
        "imbalances" to "dengesizlikler",
        "fluctuations" to "dalgalanmalar",
        "exchange" to "Takas-Değişim",
        "rates" to "Kurları-Oran",
        "international" to "uluslararası",
        "movements" to "hareketler",
        "influence" to "Etkilemek",
        "levels" to "seviyeler",
        "Government" to "Hükümet",
        "policies" to "politikalar",
        "taxation" to "vergilendirme",
        "exacerbate" to "kötüleştirebilir",
        "pressures" to "baskılar",
        "Furthermore" to "Ayrıca",
        "expectations" to "klentiler",
        "future" to "gelecek",
        "ad" to "Uymak-Ayarlamak",
        "havior" to "davranışlar",
        "accordingly" to "buna göre",
        "Natural" to "Doğal",
        "disasters" to "Afetler-Felaketler",
        "unforeseen" to "klenmeyen",
        "events" to "olaylar",
        "disrupt" to "kesintiye",
        "chains" to "zincirler",
        "damage" to "zarar",
        "infrastructure" to "altyapıya",
        "certain" to "lirli",
        "Finally" to "Son olarak",
        "wages" to "Ücretler-İşgücü maliyeti-Yevmiye",
        "salaries" to "Maaşlar",
        "contribute" to "bulunabilir",
        "inflationary" to "enflasyonist",
        "pressures" to "baskılar",
        "raising" to "arttırarak",
        "production" to "üretim",
        "Matches" to "Kibritler",
        "contain" to "İçerir-Kapsar",
        "flammable" to "yanıcı",
        "chemicals" to "Kimyasallar",
        "should" to "gerekli",
        "led" to "kullanılmak",
        "care" to "Bakım(isim)-İlgilenmek(fiil)",
        "Inhaling" to "Soluma",
        "smoke" to "Duman",
        "igniting" to "ateşlemek",
        "flammable" to "yanıcı",
        "materials" to "malzemeleri",
        "known" to "bilinir",
        "matches" to "kibritlerin",
        "be" to "olmak",
        "health" to "Sağlık",
        "Additionally" to "Ayrıca",
        "incorrectly" to "yanlış",
        "stored" to "saklanmış",
        "unsafely" to "güvensizce",
        "fire" to "Yangın",
        "Therefore" to "Bu nedenle",
        "important" to "önemlidir",
        "store" to "Saklamak",
        "safely" to "Güvenli",
        "However" to "Ancak",
        "correctly" to "Doğru",
        "kids" to "Çocuklar",
        "light" to "Yakmak-Işık",
        "pretending" to "-Yapar- 'mış gibi",
        "like" to "Gibi(isim)-Hoşlanmak(fiil)",
        "cigarettes" to "sigaralar",
        "old" to "eski",
        "mistakenly" to "yanlışlıkla",
        "myth" to "Efsane",
        "swallow" to "Yutmak",
        "average" to "ortalama",
        "7" to "7",
        "spiders" to "Örümcekler",
        "per" to "her",
        "sleeping" to "uyurken",
        "However" to "Ancak",
        "claim" to "iddia",
        "entirely" to "tamamen",
        "false" to "yanlış",
        "lacks" to "yok",
        "any" to "herhangi",
        "basis" to "dayanak",
        "idea" to "fikir",
        "likely" to "muhtemelen",
        "originated" to "kaynaklandı",
        "urban" to "şehir",
        "legend" to "Efsane",
        "illustrate" to "göstermek",
        "misinformation" to "yanlış bilginin",
        "spreads" to "yayılır",
        "rapidly" to "hızla",
        "reality" to "gerçekte",
        "likelihood" to "olasılığı",
        "swallowing" to "yutma",
        "asleep" to "uyurken",
        "extremely" to "son derece",
        "low" to "düşük",
        "bodies" to "vücudumuz",
        "natural" to "doğal",
        "reflexes" to "reflekslere",
        "even" to "hatta",
        "sleep" to "uyku",
        "prevent" to "önlemek",
        "foreign" to "yabancı",
        "objects" to "cisimlerin",
        "entering" to "girmesini",
        "mouths" to "Ağızlar",
        "Additionally" to "Ayrıca",
        "inclined" to "eğilimli",
        "crawl" to "girmek",
        "easily" to "kolayca",
        "misconceptions" to "yanlış anlamalar",
        "ingrained" to "yerleşebilir",
        "popular" to "popüler",
        "lief" to "inanış",
        "despite" to "rağmen",
        "lacking" to "-siz",
        "factual" to "gerçek",
        "evidence" to "kanıt",
        "Therefore" to "Bu nedenle",
        "individuals" to "bireyler",
        "concerned" to "endişeli",
        "inadvertently" to "istemeden",
        "sleeping" to "uyurken",
        "purely" to "tamamen",

        //avovado
        "Avocado" to "Avokado",
        "very" to "Çok",
        "useful" to "Faydalı",
        "fruit" to "Meyve",
        "benefits" to "Faydalar",
        "Firstly" to "Öncelikle",
        "rich" to "Zengindir",
        "healthy" to "Sağlıklı",
        "fats" to "Yağlar",
        "especially" to "Özellikle",
        "monounsaturated" to "Tekli doymamış",
        "heart" to "Kalp",
        "important" to "Önemli",
        "vitamins" to "Vitaminler",
        "minerals" to "Mineraller",
        "potassium" to "Potasyum",
        "vitamin C" to "C vitamini",
        "vitamin K" to "K vitamini",
        "folate" to "Folik asit",
        "vitamin E" to "E vitamini",
        "Avocado" to "Avokado",
        "fiber" to "Lif",
        "helps" to "Yardımcı olur",
        "digestion" to "Sindirim",
        "makes" to "Yapar",
        "antioxidants" to "Antioksidanlar",
        "protect" to "Korumak",
        "cells" to "Hücreler",
        "damage" to "Zarar",
        "control" to "Kontrol",
        "weight" to "Kilo",
        "feel" to "Hissetmek",
        "full" to "Tok-Tam",
        "reduces" to "Azaltır",
        "cravings" to "İstekler",
        "unhealthy" to "Sağlıksız",
        "snacks" to "Atıştırmalıklar",
        "Moreover" to "Ayrıca",
        "skin" to "Cilt",
        "hair" to "Saç",
        "healthy" to "Sağlıklı",
        "fats" to "Yağlar",
        "nutrients" to "Besinler",
        "Overall" to "Genel",
        "avocado" to "Avokado",
        "food" to "Gıda-Yiyecek",
        "part" to "Parça",
        "balanced" to "Dengeli",
        "diet" to "Diyet",
        "Calories" to "Kaloriler",
        "Fat" to "Yağ",
        "Saturated" to "Doymuş",
        "Trans" to "Trans",
        "Cholesterol" to "Kolesterol",
        "Sodium" to "Sodyum",
        "Carbohydrates" to "Karbonhidratlar",
        "Dietary" to "Diyet",
        "Sugars" to "Şekerler",
        "Protein" to "Protein",
        //NotesFromUnderground
        "I" to "Ben",
        "am" to "Yardımcı Fiil",
        "sick" to "Hasta",
        "spiteful" to "Kin",
        "unattractive" to "Çekici olmayan",
        "my" to "Benim",
        "liver" to "Karaciğer",
        "diseased" to "Hastalıklı",
        "know" to "Bilmek",
        "nothing" to "Hiçbir şey",
        "disease" to "Hastalık",
        "not" to "Değil",
        "certain" to "Kesin",
        "ails" to "Rahatsız ediyor",
        "me" to "Beni",
        "dont" to "Olumsuz yardımcı fiil",
        "consult" to "Danışmak",
        "doctor" to "Doktor",
        "never" to "Hiçbir zaman",
        "respect" to "Saygı-E.Ç",
        "doctors" to "Doktorlar",
        "Besides" to "Ayrıca",
        "extremely" to "Son Derece",
        "superstitious" to "Batıl inançlı",
        "sufficiently" to "Yeterince",
        "anyway" to "Her neyse",
        "educated" to "Eğitimli",
        "enough" to "Yeterince",
        "refuse" to "Reddetmek",
        "probably" to "Muhtemelen",
        "well" to "Pekala",
        "though" to "Ancak",
        //madagaskar
        "Madagascar" to "Madagaskar",
        "large" to "büyük",
        "island" to "ada",
        "located" to "Bulunan-Yerini Belirlemek",
        "Indian" to "Hint",
        "Ocean" to "Okyanusu",
        "unique" to "eşsiz",
        "natural" to "doğal",
        "life" to "hayat",
        "plant" to "bitki",
        "species" to "tür",
        "found" to "bulunmak",
        "anywhere" to "herhangi bir yerde",
        "else" to "başka",
        "world" to "dünya",
        "most" to "en",
        "best" to "En iyi",
        "iconic" to "sembolik",
        "lemur" to "lemur",
        "which" to "hangi",
        "only" to "sadece",
        "on" to "üzerinde",
        "rich" to "zengin",
        "diversity" to "çeşitlilik",
        "plants" to "bitkiler",
        "12,000" to "12,000",
        "species" to "türler",
        "80%" to "%80",
        "Masoala" to "Masoala",
        "Rainforest" to "Yağmur Ormanı",
        "second" to "ikinci",
        "largest" to "en büyük",
        "protected" to "korunan",
        "rainforest" to "yağmur ormanı",
        "here" to "burada",
        "preserve" to "korumak",
        "biological" to "biyolojik",
        "boasts" to "övünür",
        "diverse" to "çeşitli",
        "geographical" to "coğrafi",
        "features" to "özellikler",
        "ranging" to "arasında değişen",
        "tropical" to "tropikal",
        "dry" to "kuru",
        "savannas" to "savannalar",
        "mountainous" to "dağlık",
        "areas" to "alanlar",
        "sandy" to "kumlu",
        "beaches" to "plajlar",
        "first" to "ilk",
        "inhabitants" to "sakinler",
        "migrated" to "göç etti",
        "Southeast" to "Güneydoğu",
        "Asia" to "Asya",
        "around" to "Etrafında",
        "3500" to "3500",
        "making" to "yapmak",
        "Malagasy" to "Malgaş",
        "ethnic" to "etnik",
        "group" to "grup",
        "Southeast" to "Güneydoğu",
        "Asian" to "Asyalı",
        "origin" to "köken",
        //dualipa
        "born" to "doğdu",
        "London" to "Londra",
        "Anesa" to "Anesa",
        "Dukagjin" to "Dukagjin",
        "fled" to "kaçtı",
        "Kosovo" to "Kosova",
        "start" to "Başlangıç",
        "Bosnian" to "Bosna",
        "War" to "Savaş",
        "eldest" to "en büyük",
        "children" to "çocuklar",
        "younger" to "daha genç",
        "sister" to "kız kardeş",
        "brother" to "erkek kardeş",
        "Gjin" to "Gjin",
        "family" to "aile",
        "returned" to "geri döndü",
        "back" to "geri",
        "own" to "kendi",
        "age" to "yaş",
        "attended" to "katıldı",
        "prestigious" to "prestijli",
        "Sylvia" to "Sylvia",
        "Young" to "Genç",
        "Theatre" to "Tiyatro",
        "School" to "Okul",
        "began" to "başladı",
        "pursuing" to "takip etmek",
        "career" to "kariyer",
        "music" to "müzik",
        "between" to "arasında",
        "waiting" to "beklemek",
        "tables" to "masalar",
        "working" to "çalışmak",
        "model" to "model",
        "posted" to "gönderdi",
        "original" to "orijinal",
        "songs" to "şarkılar",
        "covers" to "kapağı",
        "YouTube" to "YouTube",
        "streaming" to "akış",
        "service" to "hizmet",
        "SoundCloud" to "SoundCloud",
        "signed" to "imzalandı",
        "agent" to "Acente-Ajan",
        "2013" to "2013",
        "following" to "takip eden",
        "deal" to "anlaşma",
        "Warner" to "Warner",
        "Brothers" to "Kardeşler",
        "Lipa’s" to "Lipa’nın",
        "gained" to "kazandı",
        "traction" to "çekiş",
        "Europe" to "Avrupa",
        "singles" to "Albümsüz, tek başına çıkan şarkı anlamına gelir.",
        "New" to "Yeni",
        "Love" to "Aşk",
        "Be" to "Olmak",
        "One" to "Bir",
        //ukrayna
        "Ukraine’s" to "Ukrayna'nın",
        "parliament" to "parlamento",
        "approved" to "onayladı",
        "law" to "yasa",
        "aims" to "Amaçları",
        "facilitate" to "kolaylaştırmak",
        "recruitment" to "askere alma",
        "soldiers" to "askerler",
        "Under" to "altında",
        "men" to "erkekler",
        "aged" to "yaşında",
        "between" to "arasında",
        "required" to "gereklidir",
        "carry" to "taşımak",
        "documents" to "belgeler",
        "confirming" to "onaylayan",
        "registration" to "kayıt",
        "military" to "askeri",
        "Additionally" to "Ayrıca",
        "offers" to "teklif eder",
        "incentives" to "teşvikler",
        "cash" to "nakit",
        "bonuses" to "ikramiyeler",
        "financial" to "mali",
        "assistance" to "yardım",
        "housing" to "konut",
        "vehicles" to "araçlar",
        "government" to "hükümet",
        "emphasized" to "vurguladı",
        "urgent" to "acil",
        "need" to "ihtiyaç",
        "troops" to "askerler",
        "because" to "çünkü",
        "may" to "olabilir",
        "shortage" to "eksiklik",
        "personnel" to "personel",
        "certain" to "belirli",
        "areas" to "alanlar",
        "However" to "Ancak",
        "serving" to "hizmet eden",
        "received" to "aldı",
        "disappointing" to "hayal kırıklığına uğratan",
        "news" to "haberler",
        "clause" to "madde",
        "specifies" to "belirler",
        "time" to "zaman",
        "limits" to "Sınırlar",
        "service" to "hizmet",
        "removed" to "kaldırıldı",
        "particularly" to "özellikle",
        "upsetting" to "üzücü",
        "engaged" to "meşgul",
        "combat" to "savaş",
        "since" to "den beri",
        "beginning" to "başlangıç",
        "conflict" to "çatışma",
        "decision" to "karar",
        "include" to "dahil etmek",
        "provisions" to "hükümler",
        "demobilization" to "terhis",
        "after" to "sonra",
        "specified" to "belirtilen",
        "period" to "dönem",
        "left" to "bıraktı",
        "feeling" to "hisseden",
        "uncertain" to "belirsiz",
        "future" to "gelecek",
        //genetics
        "Every" to "Her",
        "list" to "liste",
        "genetic" to "genetik",
        "inside" to "içinde",
        "your" to "senin",
        "body" to "vücudun",
        "brain" to "beynin",
        "grow" to "büyümesi",
        "Every" to "Her",
        "genetic" to "genetik",
        "code" to "kod",
        "three" to "üç",
        "billion" to "milyar",
        "letters" to "harfler",
        "specific" to "belirli",
        "Sometimes" to "Bazen",
        "order" to "sıralama",
        "letters" to "harfler",
        "changes." to "değişir",
        "change" to "değişim",
        "variation" to "değişim",
        "Scientists" to "Bilim insanları",
        "study" to "çalışır",
        "People" to "İnsanlar",
        "family" to "aile",
        "have" to "Yardımcı Fiil",
        "similar" to "benzer",
        "variations" to "değişimler",
        "situation" to "durum",
        "tells" to "söyler",
        "us" to "bize",
        "someone" to "birisi",
        "relative" to "akraba",
        "Genetic" to "Genetik",
        "test" to "test",
        "companies" to "şirketler",
        "read" to "okur",
        "genetic" to "genetik",
        "code" to "kod",
        "do" to "Yapmak-Ayrıca yardımcı fiil",
        "different" to "farklı",
        "reasons" to "nedenler",
        "For" to "Örneğin",
        "example" to "örnek",
        "adopted" to "evlatlık",
        "child" to "çocuk",
        "wants" to "istemek",
        "his" to "onun",
        "Sometimes" to "Bazen",
        "baby" to "bebek",
        "person" to "kişi",
        "will" to "Gelecek zaman yardımcı fiil",
        //eaat
        "prominent" to "önde gelen",
        "British" to "İngiliz",
        "scientist," to "bilim adamı,",
        "hosted" to "ev sahipliği yaptı",
        "dinner" to "akşam yemeği",
        "parties" to "partileri",
        "served" to "servis edildi.",
        "exotic" to "egzotik",
        "dishes" to "Yemek takımı-Bulaşıklar",
        "mouse" to "fare",
        "toast." to "Kızarmış ekmek",
        "Despite" to "Nasılsa",
        "eccentricities," to "tuhaf hallerine rağmen,",
        "significant" to "önemli",
        "contributions" to "katkılar",
        "geology" to "jeoloji",
        "paleontology." to "paleontoloji.",
        "became" to "oldu",
        "study" to "çalışmak",
        "geology" to "jeoloji",
        "University" to "Üniversitesi'nde",
        "Oxford." to "Oxford Üniversitesi'nde.",
        "challenged" to "meydan okudu",
        "traditional" to "geleneksel",
        "beliefs," to "inançları,",
        "including" to "dahil",
        "biblical" to "kitabi",
        "account" to "hesap",
        "Great" to "Büyük",
        "Flood," to "Tufan,",
        "examining" to "inceleyerek",
        "fossils." to "fosiller.",
        "discoveries," to "keşifleri,",
        "Megalosaurus," to "Megalosaurus,",
        "advance" to "ilerletmek",
        "understanding" to "anlayışını",
        "dinosaurs" to "dinozorlar",
        "evolution." to "evrim.",
        "crucial" to "önemli",
        "role" to "rol",
        "scientific" to "bilimsel",
        "endeavors." to "çabaları.",
        "Although" to "Nasıl ki",
        "Buckland’s" to "Buckland’ın",
        "dream" to "Rüya",
        "eat" to "yemek",
        "Earth" to "Dünya",
        "remained" to "kaldı",
        "unfulfilled," to "yerine getirilmedi,",
        "Micro-apartments" to "Mikro-daireler",
        "very" to "çok",
        "small" to "küçük",
        "few" to "az",
        "amenities" to "olanaklar",
        "little" to "az",
        "space" to "alan",
        "many" to "birçok",
        "comforts" to "rahatlıklar",
        "associate" to "ilişkilendirir",
        "living" to "yaşamak",
        "bigger" to "büyük",
        "apartment" to "daire",
        "certainly" to "kesinlikle",
        "house." to "ev.",
        "they’re" to "onlar",
        "becoming" to "olmak",
        "increasingly" to "giderek",
        "popular" to "popüler",
        "Japanese" to "Japon",
        "capital," to "başkent,",
        "particularly" to "özellikle",
        "among" to "arasında",
        "younger" to "genç",
        "people" to "insanlar",
        "who’re" to "ki",
        "starting" to "başlamak",
        "workplace" to "işyeri",
        "afford" to "karşılamak",
        "rents" to "kiralar",
        "ordinary" to "sıradan",
        "places," to "yerler,",
        "may" to "olabilir",
        "moving" to "Taşınmak-Hareket etmek",
        "Tokyo" to "Tokyo",
        "cheap" to "ucuz",
        "stay." to "kalmak.",
        "Each" to "Her",
        "measures" to "ölçüler",
        "just" to "sadece",
        "nine" to "dokuz",
        "square" to "kare",
        "meters," to "metre,",
        "half" to "yarısı",
        "size" to "boyut",
        "typical" to "tipik",
        "studio" to "stüdyo",
        "benefit’s" to "Yarar-Fayda",
        "zero" to "sıfır",
        "deposit" to "depozito",
        "‘key" to "‘anahtar",
        "money’," to "para’,",
        "nonrefundable" to "iade edilemez",
        "gift" to "hediye",
        "landlord." to "ev sahibi.",
        "Monthly" to "Aylık",
        "depending" to "bağlı olarak",
        "where" to "nereye",
        "worried" to "endişeli",
        "robots" to "robotlar",
        "jobs." to "işler.",
        "Now," to "Şimdi,",
        "seems" to "Görünmek",
        "start" to "başlamak",
        "happening." to "Olmak.",
        "ChatGPT" to "ChatGPT",
        "fastest-growing" to "en hızlı büyüyen",
        "app." to "uygulama",
        "million" to "milyon",
        "active" to "aktif",
        "users" to "kullanıcılar",
        "months" to "ay",
        "after" to "sonra",
        "launching." to "başlatmak.",
        "Chatbots" to "Sohbet botları",
        "creative," to "yaratıcı,",
        "things," to "şeyler,",
        "thought" to "düşündü",
        "work" to "Çalışmak",
        "information," to "bilgi,",
        "research," to "araştırma,",
        "reports" to "raporlar",
        "commands." to "komutlar.",
        "companies" to "şirketler",
        "realize" to "fark etmek",
        "using" to "kullanmak",
        "chatbots." to "sohbet botları.",
        "Chatbots" to "Sohbet botları",
        "fast" to "hızlı",
        "need" to "ihtiyaç",
        "break." to "mola.",
        "UK" to "İngiltere",
        "law" to "hukuk",
        "already" to "zaten",
        "write" to "Yazmak",
        "legal" to "hukuki",
        "letters" to "mektuplar",
        "come" to "gelmek",
        "arguments" to "argümanlar",
        "cases," to "davalar,",
        "means" to "anlamına gelir",
        "less" to "daha az",
        "staff." to "personel.",
        //tiktok
        "TikTok" to "TikTok",
        "recommendation" to "öneri",
        "system." to "sistem.",
        "suggests" to "Öneri",
        "videos" to "videolar",
        "based" to "Dayalı-Temek",
        "TikTok" to "TikTok",
        "different." to "farklı.",
        "shows" to "gösterir",
        "videos" to "videolar",
        "which" to "ki",
        "people" to "insanlar",
        "learns" to "öğrenir",
        "fast" to "hızlı",
        "short" to "kısa",
        "videos" to "videolar",
        "also" to "ayrıca",
        "helps" to "yardımcı olur",
        "find" to "bulmak",
        "special" to "özel",
        "starts" to "başlar",
        "Douyin," to "Douyin,",
        "Chinese" to "Çinli",
        "But" to "Ama",
        "knows" to "bilir",
        "better" to "daha iyi",
        "owns" to "sahiptir-Sahip",
        "Chinese" to "Çinli",
        "company." to "şirket.",
        "China" to "Çin",
        "makes" to "yapar",
        "tricky" to "karmaşık",
        "rules" to "kurallar",
        "Now," to "Şimdi,",
        "officials" to "yetkililer",
        "ask" to "Sormak",
        "sell" to "Satmak",
        "assets." to "varlıklar.",
        "ByteDance" to "Bayt",
        "US." to "ABD."

    )

    fun translate(word: String): String {
        return translations[word] ?: "Çeviri bulunamadı"
    }
}

